### ISSUE TITLE
Support for external VFO

### ISSUE THREAD

**Issue by sm0tsc** [df8oe/mchf-github#1041]
Can we have support for external VFO via USB similar to https://store.griffintechnology.com/us/catalogsearch/result/?q=powermate or http://www.flexradio.com/amateur-products/flexcontrol/

//SM0TSC

**Comment by df8oe** [comment]
I don't own such a device (and I by myself will not buy one). But if you send me one so that I can investigate as what it identifies itself I think we can do that.
Additionally you can help us by connecting it to a Linux machine and post the result of lsusb -vv.

But pay attention:
USB host at STM32 is a very simple one. You cannot connect an USB hub to add more than one device. If you use such a plug this will prevent you from using a keyboard for RTTY and other following digital modes! Why having one input device twice and another then is impossible to connect?

73
Andreas

**Comment by sm0tsc** [comment]
I don´t currently have one. But I will try to get hold of some.. It was
just an idea popped up in my head :-)

73
Johan - SM0TSC

2017-09-09 8:19 GMT+02:00 DF8OE <notifications@github.com>:
