### ISSUE TITLE
Pwr Meter

### ISSUE THREAD

**Issue by SA6BWX** [df8oe/mchf-github#1054]
When pressing the F2 Meter button while transmitting to change between Alc, Aud and SWR graph,
The top line Pwr meter changes to S-meter still while transmitting.  Next Ptt drop and key will revert back to Pwr again.

**Comment by df8oe** [comment]
Many thanks for your report. We are already discussing a rework of the "METER SECTION" because it eats much LCD space in RX because of showing informations which are only relevant in TX. Other LCD informations are similar only neccessary in TX OR RX. So we will fix that with a complete rework aof these sections. It's a minor issue...

**Comment by SA6BWX** [comment]
Thank you for the acknowledgement of the issue.
