### ISSUE TITLE
Frequency tuning indicator question

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1146]
I under stand about the -12 khz translation, but I have seen some videos showing the line in the center of the screen.

Did I miss something??
Is there a way to get the line in the center of the screen with the translation on??

If not , why not??
Thanks,
Chuck WD8BXS

**Comment by db4ple** [comment]
Magnify ! Or Zoom (same thing)

**Comment by WD8BXS** [comment]
Magnify, or Zoom has nothing to do with my question!
I am talking about the tuning line at which the received signal is tuner, it is to the right side of the screen when –12khz translation is turned on. 
It would be nice to have it in the center of the screen as with all other radios.
Chuck

**Comment by V31KC** [comment]
I think what he means is set your Display Magnify to 2X. that puts the red line in the center for me.

**Comment by df8oe** [comment]
It is physically impossible to put tuning indicator in the middle when you look at complete received bandwidth **because of you are not receiving in the middle**. "Middle" is NON TRANSLATED - you are working in translated mode so you are "off" middle.

If you want to put it again in the middle you must fetch a saw and cut of "the longer leg". This can easier be done by magnifying. You lost some view but your marker is in the middle.

73
Andreas

**Comment by WD8BXS** [comment]
Thank you for being so candid.
73 my friend,
Chuck

**Comment by WD8BXS** [comment]
THANKS
