### ISSUE TITLE
Information and details of firmware builds. just a question.

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1160]
I update the firm ware every time a new firmware version comes out. After I download it and install it I go looking for information of what is in the update. I keep looking but I am not finding much. Where do I find the details of the update?

**Comment by df8oe** [comment]
You can find informations about every commit here:

https://github.com/df8oe/UHSDR/commits/active-devel

73
Andreas

**Comment by DD4WH** [comment]
Please also note that the newest ("daily build"/"bleeding edge") firmware versions are of an experimental nature and can have very reduced or no documentation of new features. They are also likely to have bugs and/or new (often undocumented) menu entries.
If you like to have extended documentation on implemented features, please stick to the official releases of the firmware: https://github.com/df8oe/UHSDR/releases

73 Frank

**Comment by df8oe** [comment]
Sadly because of gigantic development speed the "official releases" are mostly outdated and missing many new features. So I recommend to use the "daily builds/bleeding edges".

It is like using bleeding edge Linux. I am working with Debian unstable (!!) (which mostls is more stable than "Windows stable") and often there is no documentation - you have to do try and experiments. But that is amateur radio: EXPERIMENTAL :)

**Comment by df8oe** [comment]
If your question is answered satisfying please close issue.
