### ISSUE TITLE
Strange problem

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1176]
I have a MCHF here that is acting very strange. I am on 40 meters, display shows 7.192 USB, adn I am hearing stations that are on 7.168 **LSB**

Very strange, I don't know where to start with this one hihi

de Chuck WD8BXS

**Comment by df8oe** [comment]
Hi Chuck...

this is not a firmware issue and you can find the issue by doing some maths :) Difference between two frequencies is 24KHz - what means that you are running in Xlate -12KNz. Your problem is loacated in section mixer / quadrature LO stage. Onde of the 90° LO signals is missing or mixer IC is dead.

73
Andreas

**Comment by WD8BXS** [comment]
Great info Andreas, thanks for the quick reply!!

Chuck

**Comment by WD8BXS** [comment]
Good call, I found a mis- soldered resistor.  Thanks again,

Take care, and God Bless,
 Chuck WD8BXS

**Comment by df8oe** [comment]
;)

well done, Chuck!

73
Andreas
