### ISSUE TITLE
Bad encoder function

### ISSUE THREAD

**Issue by poporange630** [df8oe/mchf-github#1188]
Regarding issue #734 
Symptom:
Decoders and BAND selection buttons was not triggered properly or triggered at the wrong direction.
I was about to believe that it's a decoder quality issue, until I find out that, in some cases, the BAND selection button plays up too! It's not a decoder but two simple push button!
Replication:
**Decoder Part:** 
Same as Issue #734.
**Button Part:**
In some random cases, when I attempt to change band, let's say from 21mhz to 7mhz, at each press of the BAND DOWN button, the frequency change as follows: 21mhz -> 14mhz ->10mhz ->14mhz ->10mhz -> 7mhz. It looks very similar to the issue #734. Now I tend to believe this is a hidden software issue. Please let me know if I can help debugging.

**Comment by df8oe** [comment]
I don't think this is a bad encoder function - I think you are confused by your own settings you have made ;)

It is possible to store any frequency on any band storage place if you enable this in configuration menu. So you can set all band storage places to 20m frequencies and if you push BAND+ or BAND- it seems that npthing changes ;)

Because of storing frequenencies outside the band storage place can cofuse that way we have implemented a second indicator which is places in white letters right hand of dBm display box. Please try again and do not look at the read band indicator (which only shows your tuned frequency on the band storage place but not the band storage place itself). I am nearly sure if you watch the white "band storage place indicator" you will see all is working find.

**Comment by df8oe** [comment]
Is your problem gone? If so: please close issue.

**Comment by poporange630** [comment]
Unable to replicate for now, will close the issue now and if it ever
re-appears, I'll make sure I record a video.
Thank you for your help!

2017-11-24 23:01 GMT+11:00 DF8OE <notifications@github.com>:
