### ISSUE TITLE
 Line in the grid

### ISSUE THREAD

**Issue by ly2bok** [df8oe/mchf-github#1222]
There is no upper line on the screen in the grid.

**Comment by df8oe** [comment]
I cannot confirm due to insufficient informations.

My test conditions:
Waterfall or scope light
normal - not big
Firmware version 2.7.16

Please be more exactly...

**Comment by ly2bok** [comment]
http://www.qrz.lt/ly2bok/Laikinas/Grafic%20bug.jpg
So it will be clear.
Firmware version 2.7.16
Scope - big

**Comment by df8oe** [comment]
:)
I do not know how it was designed before you noticed "the bug". I never use mode BIG because important ruler where I can touch magnify mode is missing if BIG is selected :)

So for me all is ok and I think we can live with the given layout - isn't it? It's only optical and does not impact functionality... We can see it as an "improved layout".

**Comment by sp9bsl** [comment]
I think we lost it at the unification stage, it was graded colour line. Will add it later.

**Comment by db4ple** [comment]
Hi,
yes, I commented the line drawing out. If we later want it back, no problem.
