### ISSUE TITLE
Noise when using dual screen or scope screen

### ISSUE THREAD

**Issue by ac0ax** [df8oe/mchf-github#1265]
I just updated to 2.7.39. I now have a popping noise when the display is on the Dual or scope display. If I go into the menu it quits or when I use the waterfall screen. Not sure how to fix this issue

**Comment by ac0ax** [comment]
I think I found it. When I turn RX NB and DSP NR to 0 the noise quits.

**Comment by ac0ax** [comment]
IF I select the DSP fuction the noise returns. It also returns if I turn on the New noiseblanker.
 Also the TX LED stays lit with all of the Noise settings set to off. IF I turn one of them on. the LED starts to flicker.

**Comment by lb5va** [comment]
Just confirming what ac0ax writes about the TX led. On push on PTT and it is off again.

**Comment by Jmelz** [comment]
Same as above here.

**Comment by Jmelz** [comment]
Ac0ax that is.

**Comment by df8oe** [comment]
Cannot confirm at mcHF or OVI40...

**Comment by DG9BFC** [comment]
popping noise may come from noiseblanker ... but the complete nr part is in heavy development so i am guessing you can close this issue here ... try out newer fw ... we are now at 2.7.60 so your 39er version is a bit old ... grin (sometimes there are 3 or 4 version numbers a day so check regularly and report the issues allways with newest fw (or with report what changed between newest and version before)

**Comment by ac0ax** [comment]
I just installed the newest version and it seems to be gone now. thank you.
