### ISSUE TITLE
Version 2.7.44 Red TX LED

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1290]
RED TX LED stays on all the time.

**Comment by DD4WH** [comment]
No thats not true :-).
It only stays on in some occassions, if you have activated the new noise reduction and then turn the new noise reduction off. If the red LED was on during the noise reduction activity (due to you listening to a strong station), and you turn the NR off, it stays on.
Try to turn on/off the NR, until the red LED is off again or try a release version of the software.
73 Frank

**Comment by DG9BFC** [comment]
or try to tap on the tune button two times ... that also switches it off
