### ISSUE TITLE
mcHF v0.7 board rfmod-board accidentally enabled on initial upgrade

### ISSUE THREAD

**Issue by frazierjason** [df8oe/mchf-github#1358]
When I finished building my mcHF v0.7, initially it came with an old 2.5.x firmware and original M0NKA bootloader.  I had used that firmware to calibrate the radio OK and confirm the hardware, then I used dfusedemo to DFU upgrade both bootloader and firmware to the 2.7.62 / 3.4.5 binaries from github.  Upon reassembling the radio and first boot up, I was surprised to see some extra bands activated (6m, 4m, 2200 etc), and to see the radio permit tuning on 6 meters.  After a reboot, the rfmod features disappeared.

I see this is controlled in bootloader_main() by setting SRAM2_BASE+5 = 0x29 using a compile time #ifdef SBLA decision.  Same for the #ifdef SBLS beta-test flag at SRAM2_BASE+10.  There is no attempt to clear these locations if neither #ifdef is set.

If neither of these features were set at compile time, then no overwrite occurs at those SRAM locations during boot, so I am not clear why this feature every would have been accidentally enabled?  Does SRAM somehow boot dirty right after a DFU upgrade from M0NKA binaries to UHSDR?

**Comment by df8oe** [comment]
I never have had seen accidential enabling. Must be some sort of spike that has set the bit - see it as a lottery win ;) Additional bands will not be available for mcHF because of hardware does not support them. These bands will be available at OVI40. Due to testing purposes this is done via "special bootloader" at the moment. When OVI40 RF PCB is available this will be done in firmware by checking which kind of RF board is used.
