### ISSUE TITLE
S-meter

### ISSUE THREAD

**Issue by UR7FM** [df8oe/mchf-github#1387]
S-meter work not proper, even without antenna show S3-S4. Fix this problem please.

**Comment by df8oe** [comment]
At my rig there is S3 with 50R connected and that is correct. All other S values I have tested all are correct.
You see the resistor noise :)

**Comment by DD4WH** [comment]
Please inform yourself about the concept of an S- meter
https://github.com/df8oe/UHSDR/wiki/S-Meter-&-dBm-Hz-display
The noise signal is the internal noise of your receiver
You can also calibrate tje Smeter if you have an accurate reference signal.
Also a noise measurement should be given in dbm/ Hz, because otherwise it is dependent on your filter bandwidth. So an Smeter measurement of noise without stating filter bandwidth is pointless.
Happy experimenting!
Frank DD4WH

**Comment by UR7FM** [comment]
Thanks a lot for answer. Just checked with 50R dummy  with 300Hz filter S0 and -129dBm. Now clear how it work:)) I compaired with my IC7300 before. 73!

**Comment by df8oe** [comment]
This project brings us all to think about the physics which stands behind of all :)

So I close this issue.
