### ISSUE TITLE
Menu 207 LCD Auto blank function

### ISSUE THREAD

**Issue by IZ6MAF** [df8oe/mchf-github#145]
Please it's possible to restore in the firmware the menu 207 function "lcd auto blank" that's useful when we are receiving weak signal to avoid the noise produced from the display.
It would be possible activate the lcd auto blank by a combination of buttons or by a specific area of the touch screen?
Thank you very much

**Comment by df8oe** [comment]
Hello Paolo,

its back again in our daily snapshots. You can activate it via menu 207 and toggle while activated with BANDM+ POWER.

Because of we are heavily working in restructuring menu code it may last 1 or two weeks until the changes reach testing stage. You can get daily snapshots of our devel firmware from our German project page http://www.amateurfunk-sulingen.de/mchf-projekt/modifikationen#start at the bottom of the page.

vy 73
Andreas
