### ISSUE TITLE
wm8731 v TLV320AIC23

### ISSUE THREAD

**Issue by sv1it** [df8oe/mchf-github#1527]
Hi all,

can anyone confirm whether WM8731 is fully compatible with TLV320AIC23? I replaced a faulty wm8731 with the TLV320AIC23 and the mchf does not work (digital part is all ok but no receive nor transmit)

thanks

73

sv1it

**Comment by db4ple** [comment]
Hi,
this might not be the right place to ask, this question is better placed in the Yahoo NG or the I40 Forum since you will reach a much larger audience there.  

I at least have no knowledge if there is any difference or not. Does the firmware report a missing audio codec (boot screen  and/or system info menu)?

73
Danilo

**Comment by sv1it** [comment]
Hi Danilo,

No everything seems tobe ok but….

Thanks anyway and 73

Kostas

**Comment by df8oe** [comment]
These two codecs are 100% hardware and software compatible. I can confirm this because I used hundreds of them in OVI40. so it is definitely NO firmware issue.

vy 73
Andreas

**Comment by sv1it** [comment]
thanks Andreas

73
Kostas
