### ISSUE TITLE
Rework the Hilbert filters to use time-revered coefficients and a single array.

### ISSUE THREAD

**Issue by AdShea** [df8oe/mchf-github#1530]
This is mostly just a placeholder so I don't forget about it as I'm busy with other things at the moment. It should be an easy change if someone else wants to do it though.

# Overview
The Hilbert transform FIR filters could reduce their ROM footprint by half with no change in performance. The RX-Hilbert filter is already time symmetric for the I and Q legs. Instead of storing both copies of the filter, the FIR function can use the same array stepping in reverse order. This will save 800 bytes of Flash for the RX filter. The TX filter can be changed from its current 0/90 degree phase to a +45/-45 filter in order to have the same space savings. While 1.6kB isn't a huge savings, every little bit helps on the 512kB images.

**Comment by DD4WH** [comment]
Hi!
a nice idea! We are mostly using linear phase FIR filters, so they are symmetrical. 
There are two reasons, why I think that reducing the coeffs arrays to half of their size would be problematic:
* we use the ARM CMSIS DSP routines for filtering. These use pointers to the coefficient array (which is required to contain all the coeffs, not only half of them . . . ). So we would be required to either use an array in RAM, which would be filled upon startup (which is impossible, because we have no more RAM left on the small processor) or write our own FIR filter routines
* the plan is to change the main filtering to the frequency domain anyway, which will be done once we have some time :-)
So, in general, its a good idea and maybe you have something in your mind to overcome the problems that I mentioned above!?

73 Frank

**Comment by AdShea** [comment]
Original plan was to write a "fir_float_reverse" that just takes the taps in reversed order. I've done DSP code before on an STM32F407 (for motor drive PhD work) so I'm not too worried about that, but it would be more coding.

Might be a better use of my time to start hacking through the frequency domain filtering work as that would take even less flash.

**Comment by db4ple** [comment]
Hi,
honestly, I don't think it is worth the time. especially since the RAM is an even more precious resource on 192k RAMmachines (may have 512k or 1024k flash). 
I suggest to close this (but don't mind if you keep it open either).

**Comment by db4ple** [comment]
Closed due to inactivity
