### ISSUE TITLE
with H7 CPU: RTC reset after power cycle

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1563]
after UI Board restart (power cycle) RTC starts at 00:00:00
this happens with a H7 CPU only
V 2.9.47

Forum:
https://www.amateurfunk-sulingen.de/forum/index.php?board=19;action=display;threadid=1158;start=msg18442#msg18442

**Comment by db4ple** [comment]
Hi,
must be hidden in the STMCubeMX generated code (or in the settings when generating the code). I saw some changes in the RTC HAL code made by STM in the last release. Need to check (maybe I should finally attach a battery to the H7, now that we got it working. Because of this I did not notice the issue, since without battery, time always starts with 00:00:00 :-(

Danilo

**Comment by df8oe** [comment]
Same here. Never attached battery. That's why more testers are better ;)
