### ISSUE TITLE
EEPROM corruption

### ISSUE THREAD

**Issue by sp9bsl** [df8oe/mchf-github#1675]
Hello dear users,
we found an issue with EEPROM configuration memory. We found corruption of EEPROM signature in two devices: one mcHF and one OVI40 UI board. As a result of this behaviour there is "Wrong Signature" marking in MENU/System Info and lost of configuration data. 
If anyone experience this behaviour, please DO NOT REPLACE the memory with new one but report this fact here.

When the problem occurs, to help us resolve the problem please do the following:

- install a newer firmware which supports signature reset in the debug menu
- read the systems info message regarding eeprom signature, note down the shown value
- reset the EEPROM signatue
- dump the config data with the [UHSDR tool ](https://github.com/df8oe/UHSDR/wiki/Backup-and-Restore#backup--restore-on-external-computer-since-2919)
- upload the data here as ZIP

Thank you in advance!

**Comment by df8oe** [comment]
I haven't seen this on any device yet. One scenaris where corruption can occur is "lost power during write".

It is possible to see if EEPROM is electrically damaged:
Do a "Rst Conf EEPROM" in Configuration Menu". This will write 0xff to all EEPROM cells - EEPROM now behaves as a brand new one. Now power down device using power button. Power on again, and after start, power down again using power button. If everything works as expected, your EEPROM must be recognized correctly and should be in use (green letters in System Information Menu).

**Comment by sp9bsl** [comment]
Hi Andreas,
no, eeprom is not damaged, I found in my mcHF that signature (first byte of eeprom) is overwritten to 64 decimal, so writing it to 0xff and performing hardware probing completely resolved the issue. The second case (SP2GNB's OVI40 UI) is the same but I cannot determine the value of first byte, because we have tested the desoldered chip outside by write/read and forgot to dump it before... I know this issue is rare but occured in two different devices in a period of one week.

**Comment by db4ple** [comment]
@sp9bsl: Could you please provide instructions how to preserve the right data for issue forensics right in your first entry so that the chance that someone with this problems finds out what to do?
Essentially, the user has to run or install a newer firmware which supports signature reset in the debug menu, read the systems info message regarding eeprom signature, note down the shown value , reset the EEPROM signatue and dump the config data with the UHSDR tool. And upload the data here as ZIP

**Comment by m-chichikalov** [comment]
Ok, looks like I have such problem like this.
flash is 24CM02
In System info I see -> Wrong Signature/0B [not used]

"Rst Conf EEPROM" does not help.

the function [SerialEEPROM_Clear_Variable()](https://github.com/df8oe/UHSDR/blob/6ac440343e9b0dde4af2bf9207ddf3ddc2a5789a/mchf-eclipse/misc/serial_eeprom.c#L534)
https://github.com/df8oe/UHSDR/blob/6ac440343e9b0dde4af2bf9207ddf3ddc2a5789a/mchf-eclipse/misc/serial_eeprom.c#L534

ts.ser_eeprom_type = 1

so, further, because the eeprom_type is 1 the size of page evaluated as 0 in function https://github.com/df8oe/UHSDR/blob/6ac440343e9b0dde4af2bf9207ddf3ddc2a5789a/mchf-eclipse/misc/serial_eeprom.c#L307

So, retval is 0xFF00 but no one handles it and board rebooted even it was not able to write into first two bytes.

I've checked soldering, there is no issue. Maybe someone has ideas?
Did not have time to dig more deeply, maybe on weekends.

**Comment by db4ple** [comment]
Yes, our logic is wrong here. If we have a "Wrong Signature" aka ts.ser_eeprom == 1, we have to run a EEPROM detection (ignoring the Wrong Signature) if we want to write to it. So we need to do this before trying to clear the signature variable or others.

**Comment by m-chichikalov** [comment]
Ok, I fixed for me, but it's ... 

in function SerialEEPROM_Detect(); on the booting process (called from ConfigStorage_Init())

it pass conditions on line 468 and reach line 479 where it read 0x03 instead of 0xff
![](https://s8.hostingkartinok.com/uploads/images/2019/01/b4b767d8ab170c8c58169f7ea5078aa1.jpg)

I just enter 255 via debuger and here we go....  Flash detected, everything working

so, the detection algorithm not robust. Needs some work...

**Comment by m-chichikalov** [comment]
Ok, it worked until I saved settings to flash. After it, it's again become with the wrong signature...

**Comment by db4ple** [comment]
First of all, that your eeprom is being detected to have a wrong signature explains why you can't save the keyer macros -> you are on flash storage.

The code to save to flash should not have any impact on the eeprom content. It copies variables straight from eeprom to flash. 
I cannot see how this would cause the signature to be overwritten in the eeprom.
The detection code only runs detection and writtes a signature if it see 0xffff in the initial signature reading test.
There are only two places where the first two bytes of the eeprom are being written to. It is the eeprom probing code. Here we only write if the original content is 0xff (indicating an empty eeprom).  And the copying from flash, where we initialize the first two bytes with the current signature and in use information. I.e. we overwrite in theory the information with the same information already there.
Reason for this was that BulkWrite has to be EEPROM page aligned (I'll change that now, but anyway).

But we do a "stupid" thing if we save our settings: We also save the variable 0 (i.e. the signature and eeprom in use bytes) from a variable which we filled at reading the configuration at startup.
So if there is not the signature in, it gets written to the EEPROM and causes trouble.
With a little more thinking we should be able to find out in which sequence we have to run things in
order to have a wrong signature in this variable. 
If this is the case, the quick fix is to remove the variable 0 from the to be saved values list.
But it does not tell us why this works most of the time and in some cases not.
It can't be in the flash since we are not storing or reading the signature variable from flash.
