### ISSUE TITLE
Menu item missing

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1845]
The touchscreen menu is not listed in the menu over view.
Also I can't even get to the menu overview right now, maybe some one is working on it  

Chuck

**Comment by df8oe** [comment]
Hi Chuck,

I cannot confirm. On all of my radios the menu item **is** available in the menu overview and it is working. All of my radios do have touchscreen function since years so I never have taken a look on that. But maybe that is the difference: does your radio support touch function?

vy 73
Andreas

**Comment by WD8BXS** [comment]
Hi Andreas,  sorry , I meant on the automatically generated menu overview on the Wiki
![andreas](https://user-images.githubusercontent.com/25059155/79567675-a6288a80-8082-11ea-8c0a-56c547ce2e77.jpg)

**Comment by WD8BXS** [comment]
The link does not work, and the overview does not include the touchscreen menu,

Thanks,
 Chuck

**Comment by df8oe** [comment]
That pointed me to the real issue ;)

**Comment by df8oe** [comment]
Please close the issue when it is solved for you...

**Comment by WD8BXS** [comment]
The link works now, but there is still no touch screen menu listed.

**Comment by df8oe** [comment]
Can you remeber: has that ever been included before?

**Comment by WD8BXS** [comment]
Sorry, I do not remember, maybe never!!

**Comment by WD8BXS** [comment]
I know nothing about coding, but if you look at it, it looks like the touchscreen menu is supposed to be there.

**Comment by df8oe** [comment]
Hi Chuck,

I have taken a quick look at the menu_structure and the python script and I do not see any reason why it should not work. I already have checked the placements (chain) - all ok. I have renamed it (maybe the number harms - no, that' not the reason). So I think it is a problem regarding python and regular expressions (which are not my best friends ;) ). So I will leave this due to a lack of time and minor priority. Maybe someone else fetches this...

**Comment by db4ple** [comment]
The graphics already included the touch menu, it was only the table which missed the data. Reasonit uses an list of top level menu entries to order content, and MENU_MEN2TOUCH was not in this list.

**Comment by df8oe** [comment]
I have looked always at wrong python file. It is absolutely logical - if you look into the right place...
