### ISSUE TITLE
Firmware upgrade PA bias is 0, TX not possible

### ISSUE THREAD

**Issue by Hamuser** [df8oe/mchf-github#1886]
Running UHSDR Vers. D2.11.91.

Early this week received mcHF and first two days running smoothly. Today mcHF did no start. Unplugged powersupply and tried again. No luck. Did a hard reset with F1,F3,F5. 

Any suggestion how to solve above?

**Comment by df8oe** [comment]
You have to set up configuration completely from the scratch.

This affects PA bias setings, power settings, IQ-settings and so on. F1-F3-F5 resets them all to defaults (ans PA bias to ZERO due to decurity...)

vy 73
Andreas

**Comment by Hamuser** [comment]
Thks, before starting do you recommend to upgrade to latest sw version, 2.11.94?

**Comment by df8oe** [comment]
Not mandatory, but of course you can do it. It will not impact your settings.

But it is a wise idea to backup your configuration to STM flasharea using menu function. So you can restore your settings if you do have a saving issue once again. Mostly this is caused by power failing during power-off-process (saving data to EEPROM...)

vy 73
Andreas

**Comment by Hamuser** [comment]
I have downloaded the bin file and put it on usb. The usb drive is detected with band - and power. But I get an error message: error code 4 problem writing fw-mchf.old. Any suggestion? Sorry for asking but probably need steep learning curve :-).

Update 1: 
reformated the usb (16gb) FAT32 and copied the fw-mchf.bin onto it. Followed the instructions until "Release BAND- button once you see the green LED light up. Now the dumping of the whole firmware flash into MCHFOLD.BIN starts."

Update 2: mcHF does not accept 16gb usb sticks. 
Update 3: succesfull upgraded to D2.11.94 after using 1gb USB

Q: Flash size mcHF is 2048. Does it mean 4096 and higher formated drives are not accepted?

**Comment by Hamuser** [comment]
> You have to set up configuration completely from the scratch.
> 
> This affects PA bias setings, power settings, IQ-settings and so on. F1-F3-F5 resets them all to defaults (ans PA bias to ZERO due to decurity...)
> 
> vy 73
> Andreas

Andreas, it is not possible to receive a "factory"bin file as it came out of the box?

**Comment by df8oe** [comment]
The "factory bin" is what you get when you start with F1+F3+F5. All settings are individual and you *must* walk through the configuration steps now. The only thing what could have been prevented that is "you have made a configuration backup" via menu in your STM32 flash area.

It is like a hdd break at your PC or laptop: you are lucky if you have made a backup...

Flash size of mcHF is 512KB or 1024MB. Recent firmware fits into 512KB MCUs.

Best USB sticks for mcHF upgrades are very old ones - like the 1GB you used. Take always this in the future.

**Comment by Hamuser** [comment]
Moin Andreas, clear. 
Fröhliche Weihnachten und einen guten Rutsch ins Neue Jahr.

**Comment by df8oe** [comment]
I wish you the same - stay healthy!

vy 73
Andreas

**Comment by Nandell** [comment]
Hello anybody. I`m totally new in the SDR-Szene. My TRX comes from china. It works fine the first 3 weeks. Last weekend i had a qso in cw, while the TRX started new and show me the following error:
"PA Bias is 0, TX not possible. Boot Delay because of Error or Warnings" 
My internet research gives not successfully solutions. Because my know how about this SDR-Technic is`nt yet enough. Where i find a step by step instruction with a easy way to repair the littel box ? The Software-Reset with F1/F3/F5 was`nt helpful. PA Bias is 0 and not possible to chage it.
If somewhere is a german language groupe, please give me a link too.
Thank you for the help.

**Comment by df8oe** [comment]
First look at the WIKI:
https://github.com/df8oe/UHSDR/wiki

If you have not found a solution, here is a German discussion group::
https://www.amateurfunk-sulingen.de/forum/
