### ISSUE TITLE
GCC 10 at least with Eclipse MCU does not link firmware

### ISSUE THREAD

**Issue by db4ple** [df8oe/mchf-github#1895]
## Issue Data goes here (please remove text above):

Your firmware version: current active-devel 2.11.95

### Hardware 
all
### Describe the issue:

Firmware build fails during link process with error regarding multiple instances of functions / c data structures.
Firmware compiles just fine if gcc 8 or 9 is being used in the same environment.

Current workaround is to use  gcc 8 or gcc 9 as compiler.
### Your relevant settings
Build environment Eclipse 2020-12 Embedded CDT plus xpacks GCC 10.2 on Ubuntu

**Comment by df8oe** [comment]
I can confirm this using gcc10 with Makefile

I am using gcc-arm-none-eabi-8-2019-q3-update because of this version produces the smallest binaries and no other version of gcc delivers binaries which reach this size in any way. I am not talking of 1...2 % - I am talking of 30...50 %. I do not know if there is a way to reduce binary size if using higher gcc - but the size of the binary is very important for us...
