### ISSUE TITLE
CW straight key mode: use tip contact instead of ring contact

### ISSUE THREAD

**Issue by italic-r** [df8oe/mchf-github#1912]
Your firmware version: D2.11.81
Your bootloader version: 5.0.4

### The issue:
CW straight key mode requires the plug to be wired to the ring contact instead of the standard tip. Using the ring I cannot connect a mono plug (an old bug, for example) to the radio; it will continually key the radio. Using the tip (or providing a menu choice) will allow use of mono plugs.

### Your relevant settings
CW keyer mode: STR_K
CW paddle reverse: both settings prevent use

**Comment by db4ple** [comment]
Changed, as I saw you mentioned CW paddle reverse not working for you. Did you use the right connector (the one specifically for the CW Key)?

**Comment by italic-r** [comment]
Unfortunately the swap function does not do that for me. The radio still keys when i plug in a mono plug and refuses to key with a stereo wired to tip. If i plug in a paddle and toggle the swap setting, the dits and dahs will swap like i expect. This radio is secondhand so I'm not familiar with the internals yet.

**Comment by df8oe** [comment]
That cannot be changed by software. The ring is electrically connected to PTT and so it will key the radio regardless what the software does. If you want to change that you have to open the radio and modify the connetions to the plug.

**Comment by italic-r** [comment]
I'll take a look at the schematic this week and see if i can swap that. Thanks.

**Comment by db4ple** [comment]
I had a closer look into the software:, Indeed while we switch the meaning of ring and tip regarding the CW side of things, we are not switching the PTT side of things.  If you want to keep the ability to connect a paddle instead of a straight key, hardware modification will be difficult. I suggest to create a simple 3.5mm to 3.5 mm adapter for you mono plug. E.g. from a short stereo 3.5mm extension cable.

**Comment by df8oe** [comment]
You can simply swap the tip and the ring track at the paddle plug. This does not change anything in behaviour except 1) you can use a 3.5mm mono plug if you use a straight key (because of the state of the ring is ignored in setting straight key) and 2) you have to swap dit and dah in CW setings for keyer.

**Comment by italic-r** [comment]
That sounds like a perfect solution to me, and I'll be looking at doing that over the week. Thanks! I'll close this since it's actually a hardware problem.
