### ISSUE TITLE
Signal in the middle of the screen

### ISSUE THREAD

**Issue by HB9LFU** [df8oe/mchf-github#238]
Hello mcHF programmers 

I found in bandscope mode, not 2x,  there is a small unwanted signal visible in the middle of the display reaching from the bottom upwards. However, with an antenna connected it almost completely disappears. 

vy73s
Roger

**Comment by DD4WH** [comment]
Hi Roger,

in my view, that is absolutely normal and can be seen in EVERY I&Q SDR.
My explanation:
Without antenna, the AGC calculates maximum gain = maximum sensitivity.
What you see then at 0Hz (in the middle of the screen), is all your noise in your surrounding (50/60Hz hum etc.) and all the noise that the mcHF produces internally. Exactly this is the reason why you should switch on "frequency translate" in all situations. That does NOT eliminate the noise you can SEE on the display, but it eliminates all the noise you can HEAR, because your RX frequency is +-6/12kHz away from that noise.

HTH, 73 de Frank

P.S.: --> issue can be closed.
