### ISSUE TITLE
REQUEST: Voltage depenended power adjustment

### ISSUE THREAD

**Issue by dm6tt** [df8oe/mchf-github#267]
The output power depends directly from the supply voltage.
Since the supply voltage is measured, the output power could be adjusted accordingly.
This would lead in an independed choosen output power from the power supply.

This would be a nice feature form OMs that run the mcHF on different supplies (shack, battery pack, car).

73, Marcus, DM6TT

**Comment by df8oe** [comment]
Hello Marcus,

I have had this idea in July last year, too. But I investigated that:
- function is not linear
- differs to modifications
- differs in bands

So it will be _a very huge and complex_ work with again dozens of EEPROM configuration places.

Because of this I decided _not_ to implement it.

vy 73
Andreas

**Comment by db4ple** [comment]
If it cannot be put into a (set of)  formula(s), I would not want to implement it. 

If it can be put into formula(s), someone could provide these here. And we can integrate that.
That would be nice to have. 

Formula input would be the adjustment settings per Band, the available voltage. Possibly the voltage drop (i.e. internal resistance of the power source) should be considered to. Especially for not so well charged batteries connected via not so good cables, voltage drop can be significant in higher power TX. However, getting that value is a little more tricky.

73
 Danilo

**Comment by df8oe** [comment]
too much work...

vy 73
Andreas
