### ISSUE TITLE
"Reverse Touchscreen" no longer available in display menu

### ISSUE THREAD

**Issue by inlinerbutch** [df8oe/mchf-github#676]
Since FW 1.5.3 the point "Reverse Touchscreen" in Display menu is missing for 3.2 Displays. 

In FW 1.4.0 the point "Reverse Touchscreen" was last time available.

**Comment by db4ple** [comment]
It is still there but moved to the (from one perspective) more appropriate configuration menu, where all "one" time setup items are collected. Since you rarely change to orientation of the touch screen, this is appropriate. Display menu is meant for any setting which influence the actual presentation on screen but not HW settings like the touch screen controller.

73
Danilo

**Comment by inlinerbutch** [comment]
I only realized it by the fact that the initial setup in this was reseted (maybe due the Eprom issue?!) and I tried to find this point under the display menu. I will test and confirm.

Cheers,
Uwe

**Comment by inlinerbutch** [comment]
I can confirm that the  "Reverse Touchscreen" point is now in configuration menu available and works as designed.

Cheers,
Uwe
