### ISSUE TITLE
Recommended MODS

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#739]
Are the recommended MODS for the version 5 board?
Weren't some of them included in the new version?

The mod page only mentions Ver 3 or 4

**Comment by df8oe** [comment]
Some of them were included, most of them not. And sadly one mod that is an absolute "no-go" is included in 0.5: Lifetime debugging header is removed and GPIOs are used for touchscreen (which does neither work nor will it be supported in future). Touchscreen GPIOs are used for (not yet supported) WLAN-device :/ So no developer wants to use 0.5 boards because it is nearly impossible to develop firmware without lifetime debugging possibility (and it is not a good ides to diable touchscreen when you want to do debugging: you cannot debug touchscreen with this solution).

So we do not know 100% which mods are included and which not. It is a good idea to comare mod description with actual 0.5 schematic.

73 de
Andreas

**Comment by s53dz** [comment]
Well,

Out of the correctness to the author of the mcHF project Chris M0NKA it should here on the Andreas's page be pointed to his document which explains the differences:
http://www.m0nka.co.uk/wp-content/uploads/2016/03/changes_0_5.pdf
I suppose one should first read also other documents before posting biased answers. 
And here, of course, I am not talking about the mentioned changes of GPIOs, inhibiting the debug. Which change I do not support.

I must say I have managed to find and done the modifications that I found necessary to do without any big problems, however I can see that for one who just came to the project it is hard to find and decide, which to do or not.

73 Bojan S53DZ

**Comment by WD8BXS** [comment]
Thanks Bojan,
Yes it has been difficult not knowing as a newbie.

I have to wonder if I should stay with 1.4.0.stable version to be safe.

**Comment by DG9BFC** [comment]
mod on hardware and firmare changes are 2 different kind of shoes
you can (and should) use newest fw
and you should check what hw mods should be done

**Comment by WD8BXS** [comment]
OK, that sound good!!
I guess as long as my radio is working good, I don't really need any more mods hihi

**Comment by df8oe** [comment]
It is working - more or less. But maybe you do have distorted TX signal, spurious signals, too low output power and many more "small" issues. There is not ONE reason for all of this and maybe you do not have all of these issues.

Congratulations that your mcHF is working already! Now you have to look at the function in a critical way and look if some of the issues described in modifications is present at your own mcHF. It's time to put it on rail WITH ALL REELS :)

73
Andreas

**Comment by df8oe** [comment]
updating modifications page regarding 0.5 boards in WIKI is on top of 2do-list for the next time.
