### ISSUE TITLE
Power on problem

### ISSUE THREAD

**Issue by g7jiq** [df8oe/mchf-github#757]
I am running dalily builds,  and have found that the power button will turn off, but dosn't turn back on,  
Power has to be completly removed and reapplied to work.  If then turned off again the cycle is repeated.
Have rolled back to 1.5.6 and power putton operation os ok.

**Comment by db4ple** [comment]
Hi,
this is a known issue with daily builds. 
Since the introduction of a real-time-clock (RTC) modification, the existence of the mcHF RTC Mod is being autodetected. We do this by identifying the mcHF to have a backup-battery connected.

Now, for some mcHF, this detection identifies a backup battery even without this mod executed. In this case the second start tries to start the RTC oscillator. Which fails. The software waits for the  (never starting) oscillator. 

Do you have any modifications in the power supply area which could leave the STM32 3.3V line powered even after turning it off? This would explain the behavoir, since the code expects the processor to be normally fully powered down?

73
Danilo

**Comment by g7jiq** [comment]
Hi,
Many thanks for your explanation.
I have no mods to the psu section, I have only done the recomended mods to the rx and swr sections.
I wasn't aware of an RTC mod (must have missed it) and would like to add this.
If adding the rtc mod would be the easiest way to cure this, could you possibly direct me to the mod info,

Cheers 
Dave..

**Comment by df8oe** [comment]
Please take a look at the bottom of this page:

https://github.com/df8oe/mchf-github/wiki/Recommended-Modifications

73 de
Andreas

**Comment by df8oe** [comment]
Is your LCD working in parallel or SPI mode?

**Comment by db4ple** [comment]
Next daily build firmware contains a more reliable detection approach which requires the user to start the RTC. If you don't do this, the mcHF will work as if unmodified.
Instructions in the Wiki have been updated accordingly.
