### ISSUE TITLE
VFO A + B Tracking Enhancement Request

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#866]
I use VFO A for CW and VFO B for SSB most days, except when I need to work spllit.

It would be nice that when I switch to VFO A or B, it would remember the filter settings that I was using.
That doesn't sound too hard for you geniuses hihi.

Thanks,
Chuck WD8BXS

**Comment by df8oe** [comment]
It is not hard for us - but very hard for all users... Because of storage structure in EEPROM is hard coded it is not possible to add a new storage byte for doing that without loosing all your individual settings. So we do not want to implement such things until we start to implement completely new storage structure (for using memory places for ~100 "stations"). So users do loose all settings only ONE TIME ;)

73
Andreas

**Comment by WD8BXS** [comment]
I understand Andreas, thanks for considering it!!


73, Chuck WD8BXS

**Comment by df8oe** [comment]
This is a planned feature in the future. I close this issue but it is remembered!
