### ISSUE TITLE
"Bug" in software

### ISSUE THREAD

**Issue by ly2bok** [df8oe/mchf-github#909]
Good day.
We found a small "bug" in SDRmcHF program. When turning on the DSP "NR"  of transition from Tx to Rx application sometimes "freezes" and reception not working.  
This "bug" is not working steady. Helps only "power off". Tested in several machines, the result is the same.
LY2BOK, LY3BD, LY3BFN
Thanks

**Comment by df8oe** [comment]
It is known that
- NR does make function of mcHF instable and can lead to not reproducable issues
- NR does not work as expected at all (it does not reduce noise - it crunches audio)

Additionable NR eats much horsepower. We have left NR function in firmware because of 0.1% of all users "don't want to miss it". I by myself would have kicked NR out of firmware since ~1.5 years. There are many discussions (and many issue reports) regarding NR (look at Yahoo NG).

So my hint: do not use it at all. It never will work as expected and we have not found any piece of code, which can provide well functioning NR code for small MCU like STM32F4 (and I think it never will work).
